### ISSUE TITLE
Support Laravel 7

### ISSUE THREAD

**Issue by intellow** [intellow/reuse-soft-deleted-user-email#1]
Upgrade to support Laravel 7.

**Comment by intellow** [comment]
Would love to use laravel-shift to upgrade. (Saw on Twitter this may automate a PR???)

**Comment by intellow** [comment]
Maybe if I @laravel-shift this will work?

**Comment by jasonmccreary** [comment]
There's nothing automated at this time. Just my willingness to help run a custom script for anything that may be holding you back from supporting the latest version of Laravel.

**Comment by intellow** [comment]
Got it. This is so simple no need to run anything manually. Thought it was automated. 👍

________________________________

**Comment by jasonmccreary** [comment]
By Laravel 8, I hope to make it automated. At least the bumping of the dependencies.
